const EMAIL_JOB_TYPES = {
  CONTRACT_SIGNING_INVITE: "CONTRACT_SIGNING_INVITE",
  MANAGER_SIGNING_INVITE: "MANAGER_SIGNING_INVITE",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  RENEWAL_SIGNING_INVITE: "RENEWAL_SIGNING_INVITE",
  SEND_OTP: "SEND_OTP",
  WELCOME_CHECK_IN: "WELCOME_CHECK_IN",
};

module.exports = {
  EMAIL_JOB_TYPES,
};
